### ISSUE TITLE
タスク

### ISSUE THREAD

**Issue by tassei070707** [Smart-SE/sse2018-group4#17]
１．画面作成（簡易ツールがあるか確認）（千葉さん・高田さん）
２．アプリ開発（みんなで）
３．データ活用（近藤さん）

説明資料
サービスイメージ
リーンキャンパス（木村さん）
システム全体図（平重さん）

**Comment by tassei070707** [comment]
サービスイメージ→１、２、３を見て検討

**Comment by tassei07** [comment]
オリジナルが復活したので、
クローズします。
